const v1117WeaponFamilyPoseCompatibilityPoses = [
  {
    id: "V117-WF-KATANA-REST-01",
    title: "Katana Sheathed Hip Rest",
    titleTH: "Katana Sheathed Hip Rest",
    category: "weapon_action",
    uiCategory: "combat",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body elegant standing pose with calm battle presence, one hand resting near the waist or lightly touching the sheathed katana or tachi at the left hip, scabbard physically attached to the waist, other arm relaxed naturally, face unobstructed.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["katana", "tachi", "sword"],
    avoidWeaponFamilies: ["large_weapon", "greatsword", "heavy_blade", "rifle", "bow", "spear", "polearm", "hammer"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "katana_sheathed_hip",
    holdStyle: "sheathed_rest",
    restStyle: "sheathed_side",
    familySpecificItemPrompts: {
      katana: "The katana/tachi is sheathed at the left hip with the scabbard physically attached to the waist, one visible hand resting near the hilt.",
      tachi: "The tachi is sheathed at the left hip with the scabbard physically attached to the waist, one visible hand resting near the hilt.",
      sword: "The sword is sheathed at the hip with the scabbard physically attached to the waist, one visible hand resting near the hilt."
    },
    negativeAdditions: ["floating katana", "detached scabbard", "katana planted in the ground", "grounded katana tip", "upside-down katana", "weapon not held"]
  },
  {
    id: "V117-WF-KATANA-HOLD-01",
    title: "Katana Low Side Hold",
    titleTH: "Katana Low Side Hold",
    category: "weapon_action",
    uiCategory: "combat",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body elegant standing pose with moderate torso rotation, one visible hand firmly gripping the katana or tachi lowered beside the outer thigh, blade angled diagonally downward, physically connected to the hand, not planted on the ground.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["katana", "tachi", "sword"],
    avoidWeaponFamilies: ["large_weapon", "greatsword", "heavy_blade", "rifle", "bow", "spear", "polearm", "hammer"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "katana_low_side_hold",
    holdStyle: "passive_weapon_hold",
    restStyle: "low_side_hold",
    familySpecificItemPrompts: {
      katana: "One visible hand firmly grips the katana/tachi lowered beside the outer thigh, blade angled diagonally downward, physically connected to the hand.",
      tachi: "One visible hand firmly grips the tachi lowered beside the outer thigh, blade angled diagonally downward, physically connected to the hand.",
      sword: "One visible hand firmly grips the sword lowered beside the outer thigh, blade angled diagonally downward, physically connected to the hand."
    },
    negativeAdditions: ["floating katana", "katana planted in the ground", "grounded katana tip", "upside-down katana", "weapon not held"]
  },
  {
    id: "V117-WF-HEAVY-REST-01",
    title: "Greatsword Grounded Rest",
    titleTH: "Greatsword Grounded Rest",
    category: "weapon_action",
    uiCategory: "long_item",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body strong standing pose, both hands or one visible hand supporting a heavy greatsword, hammer, axe, or mace resting naturally beside the body, tip or head grounded with visible weight, not floating, not crossing the face or torso.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["large_weapon", "greatsword", "heavy_blade", "hammer", "axe", "mace"],
    avoidWeaponFamilies: ["katana", "tachi", "bow", "rifle", "gun", "dagger"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "greatsword_grounded_rest",
    holdStyle: "passive_weapon_hold",
    restStyle: "grounded_vertical",
    familySpecificItemPrompts: {
      large_weapon: "The heavy weapon rests beside the body with visible weight, supported by one or both visible hands, with the tip or head naturally grounded.",
      greatsword: "The heavy greatsword rests beside the body with visible weight, supported by one or both visible hands, blade tip naturally grounded.",
      hammer: "The hammer or mallet rests with its head lowered beside the body, visibly supported by one or both hands, not floating.",
      axe: "The axe rests with its head lowered beside the body, visibly supported by one or both hands, not floating.",
      mace: "The mace rests with its head lowered beside the body, visibly supported by one or both hands, not floating."
    },
    negativeAdditions: ["weightless oversized weapon", "floating heavy weapon", "weapon not held", "extra weapon"]
  },
  {
    id: "V117-WF-BOW-CARRY-01",
    title: "Bow Relaxed Side Carry",
    titleTH: "Bow Relaxed Side Carry",
    category: "weapon_action",
    uiCategory: "combat",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body relaxed archer stance, one visible hand holding the bow lowered beside the outer thigh, bow not drawn, not vertically planted, not crossing the face or torso.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["bow", "longbow", "yumi"],
    avoidWeaponFamilies: ["katana", "tachi", "sword", "large_weapon", "greatsword", "spear", "rifle", "gun"],
    riskHints: ["ranged_safe"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "bow_low_side_carry",
    holdStyle: "passive_weapon_hold",
    restStyle: "relaxed_carry",
    familySpecificItemPrompts: {
      bow: "The bow is lowered beside the outer thigh and held in one visible hand, not drawn, not vertically planted, not crossing the face or torso.",
      longbow: "The longbow is lowered beside the outer thigh and held in one visible hand, not drawn, not vertically planted, not crossing the face or torso.",
      yumi: "The yumi bow is lowered beside the outer thigh and held in one visible hand, not drawn, not vertically planted, not crossing the face or torso."
    },
    negativeAdditions: ["bow planted like staff", "bow crossing face", "bow used as sword", "floating bow", "extra bow"]
  },
  {
    id: "V117-WF-SPEAR-REST-01",
    title: "Spear Upright Rest",
    titleTH: "Spear Upright Rest",
    category: "weapon_action",
    uiCategory: "long_item",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body poised warrior stance, one visible hand gripping the spear or polearm shaft upright beside the body, base naturally grounded or angled near the outer frame, face and torso unobstructed.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["spear", "polearm", "naginata", "lance", "trident"],
    avoidWeaponFamilies: ["katana", "tachi", "sword", "bow", "rifle", "gun", "dagger"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "spear_upright_rest",
    holdStyle: "passive_weapon_hold",
    restStyle: "upright_staff",
    familySpecificItemPrompts: {
      spear: "The spear or polearm is held upright beside the body with one visible hand gripping the shaft, the base naturally grounded or angled beside the frame.",
      polearm: "The polearm is held upright beside the body with one visible hand gripping the shaft, the base naturally grounded or angled beside the frame.",
      naginata: "The naginata is held upright beside the body with one visible hand gripping the shaft, the base naturally grounded or angled beside the frame.",
      lance: "The lance is held upright beside the body with one visible hand gripping the shaft, the base naturally grounded or angled beside the frame.",
      trident: "The trident is held upright beside the body with one visible hand gripping the shaft, the base naturally grounded or angled beside the frame."
    },
    negativeAdditions: ["floating spear", "detached polearm", "weapon not held", "weapon covering face"]
  },
  {
    id: "V117-WF-RIFLE-CARRY-01",
    title: "Rifle Low Carry",
    titleTH: "Rifle Low Carry",
    category: "weapon_action",
    uiCategory: "combat",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body relaxed tactical stance, rifle carried low across the lower body or slung beside the shoulder, not aiming across the face, not crossing the chest silhouette.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["rifle", "long_gun"],
    avoidWeaponFamilies: ["katana", "tachi", "sword", "large_weapon", "spear", "bow", "gun", "dagger"],
    riskHints: ["ranged_safe"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "rifle_low_carry",
    holdStyle: "passive_weapon_hold",
    restStyle: "low_carry",
    familySpecificItemPrompts: {
      rifle: "The rifle is carried low across the lower body or slung beside the shoulder, not aiming across the face and not crossing the chest silhouette.",
      long_gun: "The long gun is carried low across the lower body or slung beside the shoulder, not aiming across the face and not crossing the chest silhouette."
    },
    negativeAdditions: ["gun crossing face", "rifle covering chest", "extra gun", "floating gun", "floating rifle"]
  },
  {
    id: "V117-WF-DAGGER-HOLD-01",
    title: "Dagger Low Side Hold",
    titleTH: "Dagger Low Side Hold",
    category: "weapon_action",
    uiCategory: "combat",
    subcategory: "passive_weapon_hold",
    framing: "full_body",
    intensity: "safe",
    prompt: "Full-body compact rogue stance, one visible hand holding a dagger low beside the outer thigh, small blade clearly separated from the body, not raised across the face or chest.",
    requiresItem: true,
    noItemSafe: false,
    itemActionType: "passive_weapon_hold",
    compatibleItemRoles: ["weapon"],
    avoidItemRoles: ["instrument_item", "document_item", "daily_item", "accessory_item", "tool_item", "prop", "none"],
    compatibleWeaponFamilies: ["dagger", "knife"],
    avoidWeaponFamilies: ["large_weapon", "greatsword", "katana", "tachi", "bow", "rifle", "spear"],
    weaponHandPlacement: true,
    explicitItemHold: true,
    weaponPresentation: "dagger_low_side_hold",
    holdStyle: "passive_weapon_hold",
    restStyle: "low_side_hold",
    familySpecificItemPrompts: {
      dagger: "The dagger is held low beside the outer thigh in one visible hand, small and clearly separated from the body.",
      knife: "The knife is held low beside the outer thigh in one visible hand, small and clearly separated from the body."
    },
    negativeAdditions: ["floating dagger", "extra dagger", "dagger crossing face", "weapon not held"]
  }
];

if (typeof window !== "undefined") { window.v1117WeaponFamilyPoseCompatibilityPoses = v1117WeaponFamilyPoseCompatibilityPoses; }

if (typeof module !== "undefined" && module.exports) { module.exports = { v1117WeaponFamilyPoseCompatibilityPoses }; }
